spring.application.name=webcrawler
server.port=${PORT:8080}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Neon PostgreSQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-icy-bonus-a7ny1zzn-pooler.ap-southeast-2.aws.neon.tech:5432/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.ssn.webcrawler=INFO
